In [21]:
import pandas as pd

In [24]:
df = pd.read_csv('Practice_Data.csv')

In [25]:
df.head()

,Student_ID,Name,Age,Gender,City,Department,Semester,Hostel,Attendance_%,Study_Hours_Daily,...,Midterm_Marks,Final_Exam_Marks,Project_Marks,Coding_Score,Communication_Score,Sleep_Hours,Screen_Time_Hours,Annual_Fees,Grade,Attendance_Status
0,STU1001,Aditya,23,Male,Delhi,Mechanical,6,No,71.9,1.0,...,49,90,60,94,53.0,7.3,6.9,141932,B,Irregular
1,STU1002,Varun,23,Male,Mumbai,Mechanical,7,No,74.4,5.1,...,83,88,81,79,44.0,7.2,3.4,150038,B+,Irregular
2,STU1003,Vivaan,21,Female,Chennai,Mechanical,5,No,55.6,1.2,...,94,43,89,28,NaN,5.7,7.3,89457,B,Irregular
3,STU1004,Aryan,21,Female,Ahmedabad,AI & DS,4,No,74.1,6.1,...,88,33,93,82,47.0,7.1,6.2,159789,B,Irregular
4,STU1005,Harsh,22,Male,Haridwar,CSE,8,Yes,69.6,2.4,...,87,53,65,79,70.0,8.2,7.7,83986,B+,Irregular

In [26]:
df.tail()

,Student_ID,Name,Age,Gender,City,Department,Semester,Hostel,Attendance_%,Study_Hours_Daily,...,Midterm_Marks,Final_Exam_Marks,Project_Marks,Coding_Score,Communication_Score,Sleep_Hours,Screen_Time_Hours,Annual_Fees,Grade,Attendance_Status
248,STU1249,Mohit,21,Female,Ahmedabad,IT,5,Yes,59.2,2.7,...,42,83,100,57,77.0,6.4,3.0,146234,B+,Irregular
249,STU1250,Simran,23,Male,Kolkata,ECE,1,No,71.2,3.2,...,88,59,99,67,64.0,6.8,2.0,116287,B+,Irregular
250,STU1011,Aryan,23,Female,Chennai,Mechanical,7,Yes,67.5,3.6,...,35,48,41,72,73.0,8.1,5.8,176081,C,Irregular
251,STU1051,Aarav,23,Female,Kolkata,ECE,5,Yes,82.5,4.8,...,98,67,76,30,32.0,7.6,2.7,71342,B,Regular
252,STU1101,Aarav,21,Female,Pune,Civil,7,Yes,81.7,2.6,...,51,57,41,54,34.0,6.5,4.6,141260,D,Regular

In [27]:
df.describe()

,Age,Semester,Attendance_%,Study_Hours_Daily,Assignment_%,Midterm_Marks,Final_Exam_Marks,Project_Marks,Coding_Score,Communication_Score,Sleep_Hours,Screen_Time_Hours,Annual_Fees
count,253.000000,253.000000,253.000000,248.000000,248.000000,253.000000,253.000000,253.000000,253.000000,248.000000,253.000000,253.000000,253.000000
mean,20.545455,4.553360,77.746640,4.383871,71.472177,67.086957,63.822134,71.027668,60.778656,63.104839,6.836364,5.978261,122319.264822
std,1.730592,2.380918,12.417977,2.083398,16.045017,18.982248,19.103415,17.278623,23.528234,20.916769,1.327196,2.336826,32776.061403
min,18.000000,1.000000,55.200000,1.000000,45.200000,35.000000,30.000000,40.000000,20.000000,30.000000,4.500000,2.000000,70389.000000
25%,19.000000,2.000000,68.300000,2.600000,57.750000,52.000000,48.000000,57.000000,42.000000,43.750000,5.600000,3.800000,92015.000000
50%,21.000000,5.000000,78.200000,4.650000,70.950000,64.000000,64.000000,72.000000,60.000000,65.000000,6.900000,5.900000,126958.000000
75%,22.000000,7.000000,87.800000,6.100000,83.825000,84.000000,80.000000,86.000000,81.000000,82.000000,8.100000,8.000000,148617.000000
max,23.000000,8.000000,99.900000,8.000000,99.900000,100.000000,100.000000,100.000000,100.000000,100.000000,9.000000,10.000000,179538.000000

In [29]:
df.dtypes

Student_ID                 str
Name                       str
Age                      int64
Gender                     str
City                       str
Department                 str
Semester                 int64
Hostel                     str
Attendance_%           float64
Study_Hours_Daily      float64
Assignment_%           float64
Midterm_Marks            int64
Final_Exam_Marks         int64
Project_Marks            int64
Coding_Score             int64
Communication_Score    float64
Sleep_Hours            float64
Screen_Time_Hours      float64
Annual_Fees              int64
Grade                      str
Attendance_Status          str
dtype: object

In [31]:
df.isnull().any()

Student_ID             False
Name                   False
Age                    False
Gender                 False
City                    True
Department             False
Semester               False
Hostel                 False
Attendance_%           False
Study_Hours_Daily       True
Assignment_%            True
Midterm_Marks          False
Final_Exam_Marks       False
Project_Marks          False
Coding_Score           False
Communication_Score     True
Sleep_Hours            False
Screen_Time_Hours      False
Annual_Fees            False
Grade                  False
Attendance_Status      False
dtype: bool

In [35]:
df.isnull().sum()

Student_ID             0
Name                   0
Age                    0
Gender                 0
City                   5
Department             0
Semester               0
Hostel                 0
Attendance_%           0
Study_Hours_Daily      5
Assignment_%           5
Midterm_Marks          0
Final_Exam_Marks       0
Project_Marks          0
Coding_Score           0
Communication_Score    5
Sleep_Hours            0
Screen_Time_Hours      0
Annual_Fees            0
Grade                  0
Attendance_Status      0
dtype: int64

In [36]:
df['Study_Hours_fillna'] = df['Study_Hours_Daily'].fillna(df['Study_Hours_Daily'].mean())

In [37]:
df

,Student_ID,Name,Age,Gender,City,Department,Semester,Hostel,Attendance_%,Study_Hours_Daily,...,Final_Exam_Marks,Project_Marks,Coding_Score,Communication_Score,Sleep_Hours,Screen_Time_Hours,Annual_Fees,Grade,Attendance_Status,Study_Hours_fillna
0,STU1001,Aditya,23,Male,Delhi,Mechanical,6,No,71.9,1.0,...,90,60,94,53.0,7.3,6.9,141932,B,Irregular,1.0
1,STU1002,Varun,23,Male,Mumbai,Mechanical,7,No,74.4,5.1,...,88,81,79,44.0,7.2,3.4,150038,B+,Irregular,5.1
2,STU1003,Vivaan,21,Female,Chennai,Mechanical,5,No,55.6,1.2,...,43,89,28,NaN,5.7,7.3,89457,B,Irregular,1.2
3,STU1004,Aryan,21,Female,Ahmedabad,AI & DS,4,No,74.1,6.1,...,33,93,82,47.0,7.1,6.2,159789,B,Irregular,6.1
4,STU1005,Harsh,22,Male,Haridwar,CSE,8,Yes,69.6,2.4,...,53,65,79,70.0,8.2,7.7,83986,B+,Irregular,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,STU1249,Mohit,21,Female,Ahmedabad,IT,5,Yes,59.2,2.7,...,83,100,57,77.0,6.4,3.0,146234,B+,Irregular,2.7
249,STU1250,Simran,23,Male,Kolkata,ECE,1,No,71.2,3.2,...,59,99,67,64.0,6.8,2.0,116287,B+,Irregular,3.2
250,STU1011,Aryan,23,Female,Chennai,Mechanical,7,Yes,67.5,3.6,...,48,41,72,73.0,8.1,5.8,176081,C,Irregular,3.6
251,STU1051,Aarav,23,Female,Kolkata,ECE,5,Yes,82.5,4.8,...,67,76,30,32.0,7.6,2.7,71342,B,Regular,4.8
252,STU1101,Aarav,21,Female,Pune,Civil,7,Yes,81.7,2.6,...,57,41,54,34.0,6.5,4.6,141260,D,Regular,2.6

In [38]:
df = df.rename(columns={'Study_Hours_fillna':'New_Value_StudyHours'})

In [39]:
df

,Student_ID,Name,Age,Gender,City,Department,Semester,Hostel,Attendance_%,Study_Hours_Daily,...,Final_Exam_Marks,Project_Marks,Coding_Score,Communication_Score,Sleep_Hours,Screen_Time_Hours,Annual_Fees,Grade,Attendance_Status,New_Value_StudyHours
0,STU1001,Aditya,23,Male,Delhi,Mechanical,6,No,71.9,1.0,...,90,60,94,53.0,7.3,6.9,141932,B,Irregular,1.0
1,STU1002,Varun,23,Male,Mumbai,Mechanical,7,No,74.4,5.1,...,88,81,79,44.0,7.2,3.4,150038,B+,Irregular,5.1
2,STU1003,Vivaan,21,Female,Chennai,Mechanical,5,No,55.6,1.2,...,43,89,28,NaN,5.7,7.3,89457,B,Irregular,1.2
3,STU1004,Aryan,21,Female,Ahmedabad,AI & DS,4,No,74.1,6.1,...,33,93,82,47.0,7.1,6.2,159789,B,Irregular,6.1
4,STU1005,Harsh,22,Male,Haridwar,CSE,8,Yes,69.6,2.4,...,53,65,79,70.0,8.2,7.7,83986,B+,Irregular,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,STU1249,Mohit,21,Female,Ahmedabad,IT,5,Yes,59.2,2.7,...,83,100,57,77.0,6.4,3.0,146234,B+,Irregular,2.7
249,STU1250,Simran,23,Male,Kolkata,ECE,1,No,71.2,3.2,...,59,99,67,64.0,6.8,2.0,116287,B+,Irregular,3.2
250,STU1011,Aryan,23,Female,Chennai,Mechanical,7,Yes,67.5,3.6,...,48,41,72,73.0,8.1,5.8,176081,C,Irregular,3.6
251,STU1051,Aarav,23,Female,Kolkata,ECE,5,Yes,82.5,4.8,...,67,76,30,32.0,7.6,2.7,71342,B,Regular,4.8
252,STU1101,Aarav,21,Female,Pune,Civil,7,Yes,81.7,2.6,...,57,41,54,34.0,6.5,4.6,141260,D,Regular,2.6

In [40]:
df['New_value'] = df['Attendance_%'].fillna(df['Attendance_%'].mean()).astype(int)

In [46]:
df.head()

,Student_ID,Name,Age,Gender,City,Department,Semester,Hostel,Attendance_%,Study_Hours_Daily,...,Coding_Score,Communication_Score,Sleep_Hours,Screen_Time_Hours,Annual_Fees,Grade,Attendance_Status,New_Value_StudyHours,New_value,Value_New
0,STU1001,Aditya,23,Male,Delhi,Mechanical,6,No,71.9,1.0,...,94,53.0,7.3,6.9,141932,B,Irregular,1.0,71,143.8
1,STU1002,Varun,23,Male,Mumbai,Mechanical,7,No,74.4,5.1,...,79,44.0,7.2,3.4,150038,B+,Irregular,5.1,74,148.8
2,STU1003,Vivaan,21,Female,Chennai,Mechanical,5,No,55.6,1.2,...,28,NaN,5.7,7.3,89457,B,Irregular,1.2,55,111.2
3,STU1004,Aryan,21,Female,Ahmedabad,AI & DS,4,No,74.1,6.1,...,82,47.0,7.1,6.2,159789,B,Irregular,6.1,74,148.2
4,STU1005,Harsh,22,Male,Haridwar,CSE,8,Yes,69.6,2.4,...,79,70.0,8.2,7.7,83986,B+,Irregular,2.4,69,139.2

In [54]:
df['Value_New'] = df['New_Value'].apply(lambda x:x*2)

KeyError: 'New_Value'

In [ ]:
df.drop('Value_New',axis=1,inplace=True)

KeyError: "['Value_New'] not found in axis"

In [51]:
df.head()

,Student_ID,Name,Age,Gender,City,Department,Semester,Hostel,Attendance_%,Study_Hours_Daily,...,Project_Marks,Coding_Score,Communication_Score,Sleep_Hours,Screen_Time_Hours,Annual_Fees,Grade,Attendance_Status,New_Value_StudyHours,New_value
0,STU1001,Aditya,23,Male,Delhi,Mechanical,6,No,71.9,1.0,...,60,94,53.0,7.3,6.9,141932,B,Irregular,1.0,71
1,STU1002,Varun,23,Male,Mumbai,Mechanical,7,No,74.4,5.1,...,81,79,44.0,7.2,3.4,150038,B+,Irregular,5.1,74
2,STU1003,Vivaan,21,Female,Chennai,Mechanical,5,No,55.6,1.2,...,89,28,NaN,5.7,7.3,89457,B,Irregular,1.2,55
3,STU1004,Aryan,21,Female,Ahmedabad,AI & DS,4,No,74.1,6.1,...,93,82,47.0,7.1,6.2,159789,B,Irregular,6.1,74
4,STU1005,Harsh,22,Male,Haridwar,CSE,8,Yes,69.6,2.4,...,65,79,70.0,8.2,7.7,83986,B+,Irregular,2.4,69

In [55]:
df['Value_New'] = df['New_value'].apply(lambda x:x*2)

In [56]:
df.head()

,Student_ID,Name,Age,Gender,City,Department,Semester,Hostel,Attendance_%,Study_Hours_Daily,...,Coding_Score,Communication_Score,Sleep_Hours,Screen_Time_Hours,Annual_Fees,Grade,Attendance_Status,New_Value_StudyHours,New_value,Value_New
0,STU1001,Aditya,23,Male,Delhi,Mechanical,6,No,71.9,1.0,...,94,53.0,7.3,6.9,141932,B,Irregular,1.0,71,142
1,STU1002,Varun,23,Male,Mumbai,Mechanical,7,No,74.4,5.1,...,79,44.0,7.2,3.4,150038,B+,Irregular,5.1,74,148
2,STU1003,Vivaan,21,Female,Chennai,Mechanical,5,No,55.6,1.2,...,28,NaN,5.7,7.3,89457,B,Irregular,1.2,55,110
3,STU1004,Aryan,21,Female,Ahmedabad,AI & DS,4,No,74.1,6.1,...,82,47.0,7.1,6.2,159789,B,Irregular,6.1,74,148
4,STU1005,Harsh,22,Male,Haridwar,CSE,8,Yes,69.6,2.4,...,79,70.0,8.2,7.7,83986,B+,Irregular,2.4,69,138

In [57]:
df.dtypes

Student_ID                  str
Name                        str
Age                       int64
Gender                      str
City                        str
Department                  str
Semester                  int64
Hostel                      str
Attendance_%            float64
Study_Hours_Daily       float64
Assignment_%            float64
Midterm_Marks             int64
Final_Exam_Marks          int64
Project_Marks             int64
Coding_Score              int64
Communication_Score     float64
Sleep_Hours             float64
Screen_Time_Hours       float64
Annual_Fees               int64
Grade                       str
Attendance_Status           str
New_Value_StudyHours    float64
New_value                 int64
Value_New                 int64
dtype: object

In [60]:
grouped_mean = df.groupby('Gender')['Midterm_Marks'].mean()
print(grouped_mean)

Gender
Female    67.582609
Male      66.673913
Name: Midterm_Marks, dtype: float64

In [62]:
grouped_mean = df.groupby('City')['Project_Marks'].mean()
print(grouped_mean)

City
Ahmedabad    70.206897
Bangalore    72.518519
Chennai      75.421053
Delhi        62.956522
Haridwar     79.730769
Hyderabad    65.880000
Jaipur       75.434783
Kolkata      71.640000
Mumbai       66.055556
Pune         71.606061
Name: Project_Marks, dtype: float64

In [64]:
grouped_mean = df.groupby(['City','Gender'])['Project_Marks'].mean()
print(grouped_mean)

City       Gender
Ahmedabad  Female    75.785714
           Male      65.000000
Bangalore  Female    76.769231
           Male      68.571429
Chennai    Female    74.769231
           Male      76.833333
Delhi      Female    70.777778
           Male      57.928571
Haridwar   Female    80.083333
           Male      79.428571
Hyderabad  Female    64.875000
           Male      67.666667
Jaipur     Female    70.000000
           Male      78.333333
Kolkata    Female    75.000000
           Male      70.058824
Mumbai     Female    67.600000
           Male      65.461538
Pune       Female    69.375000
           Male      73.705882
Name: Project_Marks, dtype: float64

In [67]:
grouped_mean = df.groupby('City')[['Project_Marks','Midterm_Marks']].mean()
print(grouped_mean)

           Project_Marks  Midterm_Marks
City
Ahmedabad      70.206897      69.551724
Bangalore      72.518519      71.333333
Chennai        75.421053      64.368421
Delhi          62.956522      58.565217
Haridwar       79.730769      69.384615
Hyderabad      65.880000      67.400000
Jaipur         75.434783      65.043478
Kolkata        71.640000      71.440000
Mumbai         66.055556      64.666667
Pune           71.606061      66.272727

In [72]:
grouped = df.groupby(['City','Gender'])['Project_Marks'].agg(['mean','count','sum'])
print(grouped)

                       mean  count   sum
City      Gender
Ahmedabad Female  75.785714     14  1061
          Male    65.000000     15   975
Bangalore Female  76.769231     13   998
          Male    68.571429     14   960
Chennai   Female  74.769231     13   972
          Male    76.833333      6   461
Delhi     Female  70.777778      9   637
          Male    57.928571     14   811
Haridwar  Female  80.083333     12   961
          Male    79.428571     14  1112
Hyderabad Female  64.875000     16  1038
          Male    67.666667      9   609
Jaipur    Female  70.000000      8   560
          Male    78.333333     15  1175
Kolkata   Female  75.000000      8   600
          Male    70.058824     17  1191
Mumbai    Female  67.600000      5   338
          Male    65.461538     13   851
Pune      Female  69.375000     16  1110
          Male    73.705882     17  1253

In [76]:
## Merging and Joining Data Frames
df1 = pd.DataFrame({'key':['A','B','C'],'Value1':[1,2,3]})
df2 = pd.DataFrame({'key':['A','B','D'],'Value2':[4,5,6]})

In [77]:
df1

  key  Value1
0   A       1
1   B       2
2   C       3

In [78]:
df2

  key  Value2
0   A       4
1   B       5
2   D       6

In [80]:
pd.merge(df1,df2,on='key',how='inner')

  key  Value1  Value2
0   A       1       4
1   B       2       5

In [81]:
pd.merge(df1,df2,on='key',how='outer')

  key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [82]:
pd.merge(df1,df2,on='key',how='left')

  key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [83]:
pd.merge(df1,df2,on='key',how='right')

  key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6